version: '3.8'

services:
  backend:
    build:
      context: ./checkout
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./checkout:/var/www
    networks:
      - app_network
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=checkout
      - DB_USERNAME=toro
      - DB_PASSWORD=seduto
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: checkout
      MYSQL_USER: toro
      MYSQL_PASSWORD: seduto
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./checkout:/var/www
    depends_on:
      - backend
    networks:
      - app_network

  frontend:
    build:
      context: ./checkout-frontend
    container_name: nuxt_app
    working_dir: /app
    volumes:
      - ./checkout-frontend:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    networks:
      - app_network
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
